services:
  - type: web
    name: myday
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn myday.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myday-db
          property: connectionString

databases:
  - name: myday-db
    databaseName: myday
    plan: free
