services:
  - type: web
    name: myday
    env: python
    plan: free
    buildCommand: chmod +x render_build.sh && ./render_build.sh
    startCommand: gunicorn myday.wsgi:application --workers=1 --threads=8 --timeout=0
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myday-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: myday-db
    databaseName: myday
    plan: free
